# Generated by Django 4.0 on 2024-05-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
