---
name: Django CI with Tests and Linting

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    test-lint:
      name: Test and Lint
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2

        - name: Set up Python 3.9
          uses: actions/setup-python@v2
          with:
            python-version: '3.9'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Run tests
          run: |
            python app/manage.py test

        - name: Lint with Flake8
          run: |
            flake8 .